f1=int(input("enter marks 1 :"))
f2=int(input("enter marks 2 :"))
f3=int(input("enter marks 3 :"))
f4=int(input("enter marks 4 :"))
f5=int(input("enter marks 5 :"))
f6=int(input("enter marks 6 :"))
marks=[f1,f2,f3,f4,f5,f6,]
print(marks)
marks.sort()
print(marks)